/* Generated by Cython 0.28.2 */

#ifndef __PYX_HAVE__correlations__utils
#define __PYX_HAVE__correlations__utils


#ifndef __PYX_HAVE_API__correlations__utils

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double __pyx_f_12correlations_5utils_integrand(double, double, double, int, int, int, int, double, double, double, double, double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double __pyx_f_12correlations_5utils_integrand_lambdaCDM(double, double, int, int, int, int, double, double, double, double, double, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__correlations__utils */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initutils(void);
#else
PyMODINIT_FUNC PyInit_utils(void);
#endif

#endif /* !__PYX_HAVE__correlations__utils */
